#index:
#    path: /
#    controller: App\Controller\DefaultController::index

redirect from homepage_to_default_page:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults: 
        route: 'default_index'

